router bgp 65000
  bgp bestpath as-path multipath-relax
  no bgp ebgp-requires-policy
  bgp router-id 10.0.0.1
  neighbor jaycube-dev peer-group
  neighbor jaycube-dev remote-as external
  neighbor 10.0.6.8 peer-group jaycube-dev
  neighbor 10.0.6.9 peer-group jaycube-dev
  neighbor 10.0.6.10 peer-group jaycube-dev

  