machine:
  nodeLabels:
    role: worker
    nodepool: ${nodepool}
    bgp: "${bgp}"
  install:
    disk: ${install_disk}
  network:
    hostname: ${hostname}
  time:
    servers:
      - /dev/ptp0

  disks:
      - device: /dev/vdb # The name of the disk to use.
        partitions:
          - mountpoint: /var/lib/longhorn # Where to mount the partition.
 
  kubelet:
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
    extraConfig:
%{ if length(node_taints) > 0 ~}
      registerWithTaints:
%{ for node_taint in node_taints ~}
        - key: ${node_taint}
          effect: "NoSchedule"
          value: "true"
%{ endfor ~}
%{ endif ~}